### PR TITLE
Update dependencies, cleanup deprecated methods

### PR DESCRIPTION
**Pull request by adamdecaf**
I tried this out locally (with `-t`) and it ran fine. Thanks for the gem! 

Fixes: https://github.com/ddollar/github-backup/issues/21

### CODE REVIEW

**Comment by adamdecaf** [comment]
cc @ddollar @garethrees

**Comment by adamdecaf** [comment]
That failure was from ruby 1.9.x. Do we still need to test/build against that?

> rake-12.3.1 requires ruby version >= 2.0.0

**Comment by adamdecaf** [comment]
I can PR having travis testing against ruby 2.0 through 2.5 if y'all want.

**Comment by ddollar** [comment]
Thanks!

**Pull request merged**
